create table multipolygons (
       polygon2d geometry(MULTIPOLYGON), 
       polygon3d geometry(MULTIPOLYGONZ), 
       polygon4d geometry(MULTIPOLYGONZM)
);

insert into multipolygons (polygon2d, polygon3d, polygon4d) values (
       ST_GeomFromText('MULTIPOLYGON(((0 1, 2 3, 4 5, 0 1), 
                                         (0 1, 2 3, 4 5, 0 1), 
                                         (0 1, 2 3, 4 5, 0 1)), 
                                         ((0 1, 2 3, 4 5, 0 1), 
                                         (0 1, 2 3, 4 5, 0 1), 
                                         (0 1, 2 3, 4 5, 0 1)))'), 
       ST_GeomFromText('MULTIPOLYGON(((0 1 2, 3 4 5, 6 7 8, 0 1 2), 
                                         (0 1 2, 3 4 5, 6 7 8, 0 1 2), 
                                         (0 1 2, 3 4 5, 6 7 8, 0 1 2)), 
                                         ((0 1 2, 3 4 5, 6 7 8, 0 1 2), 
                                         (0 1 2, 3 4 5, 6 7 8, 0 1 2), 
                                         (0 1 2, 3 4 5, 6 7 8, 0 1 2)))'), 
       ST_GeomFromText('MULTIPOLYGON(((0 1 2 3, 4 5 6 7, 8 9 10 11, 0 1 2 3), 
                                         (0 1 2 3, 4 5 6 7, 8 9 10 11, 0 1 2 3), 
                                         (0 1 2 3, 4 5 6 7, 8 9 10 11, 0 1 2 3)), 
                                         ((0 1 2 3, 4 5 6 7, 8 9 10 11, 0 1 2 3), 
                                         (0 1 2 3, 4 5 6 7, 8 9 10 11, 0 1 2 3), 
                                         (0 1 2 3, 4 5 6 7, 8 9 10 11, 0 1 2 3)))')
);
