create table polygons (
       polygon2d geometry(POLYGON), 
       polygon3d geometry(POLYGONZ), 
       polygon4d geometry(POLYGONZM)
);

insert into polygons (polygon2d, polygon3d, polygon4d) values (
       ST_GeomFromText('POLYGON((0 1, 2 3, 4 5, 0 1), 
                                   (0 1, 2 3, 4 5, 0 1), 
                                   (0 1, 2 3, 4 5, 0 1))'), 
       ST_GeomFromText('POLYGON((0 1 2, 3 4 5, 6 7 8, 0 1 2), 
                                   (0 1 2, 3 4 5, 6 7 8, 0 1 2), 
                                   (0 1 2, 3 4 5, 6 7 8, 0 1 2))'), 
       ST_GeomFromText('POLYGON((0 1 2 3, 4 5 6 7, 8 9 10 11, 0 1 2 3), 
                                   (0 1 2 3, 4 5 6 7, 8 9 10 11, 0 1 2 3), 
                                   (0 1 2 3, 4 5 6 7, 8 9 10 11, 0 1 2 3))')
);
