name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - aiohttp
  - tornado
  - sqlalchemy<1.4
  - intake
  - numpy<1.20
  - requests
  - msgpack-numpy
  - pytest
  - fsspec
  - ibis-framework
  - pip
  - pytest
