name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: master

jobs:
  test:
    name: ${{ matrix.CONDA_ENV }}-pytest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CONDA_ENV: [py38, py39, py310]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup conda
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci/environment-${{ matrix.CONDA_ENV }}.yml


      - name: pip-install
        shell: bash -l {0}
        run: |
          pip install -e . --no-deps

      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest -v
